var vm = new Vue({
    el: "#app",
    data: {
        isCollapse : false,
        nowTime: '',
        type:'5',
        thp:'',
        time:'',
        loading:false,
        currentPage:1,
        tableData:[],
        tableData1: [
            {
                machine_no: '00211',
                machine_name: '	水源热泵机组1',
                machine_kind: '	水源热泵机组',
                machine_brand: 'YKGCEVP85C5G-HP',
                machine_type: '—',
                createTime: '2012-04-01',
                usedTime: '2013-01-01',
                building: '地下一层',
                room: '冷冻机房',
                status: '在用',
          },
            {
                machine_no: '00212',
                machine_name: '	水源热泵机组2',
                machine_kind: '	水源热泵机组',
                machine_brand: 'YKGCEVP85C5G-HP',
                machine_type: '—',
                createTime: '2012-04-01',
                usedTime: '2013-01-01',
                building: '地下一层',
                room: '冷冻机房',
                status: '在用',
          },
            {
                machine_no: '00213',
                machine_name: '	水源热泵机组3',
                machine_kind: '	水源热泵机组',
                machine_brand: 'YKGCEVP85C5G-HP',
                machine_type: '—',
                createTime: '2012-04-01',
                usedTime: '2013-01-01',
                building: '地下一层',
                room: '冷冻机房',
                status: '在用',
          },
            {
                machine_no: '00221',
                machine_name: '冷水机组1',
                machine_kind: '冷水机组',
                machine_brand: 'YKEDEQQ75COG',
                machine_type: '—',
                createTime: '2012-04-01',
                usedTime: '2013-01-01',
                building: '地下一层',
                room: '冷冻机房',
                status: '在用',
          },
            {
                machine_no: '00222',
                machine_name: '冷水机组2',
                machine_kind: '冷水机组',
                machine_brand: 'YKGCEVP85C5G-HP',
                machine_type: '—',
                createTime: '2012-04-01',
                usedTime: '2013-01-01',
                building: '地下一层',
                room: '冷冻机房',
                status: '在用',
          },
            {
                machine_no: '00223',
                machine_name: '冷水机组3',
                machine_kind: '冷水机组',
                machine_brand: 'YKGCEVP85C5G-HP',
                machine_type: '—',
                createTime: '2012-04-01',
                usedTime: '2013-01-01',
                building: '地下一层',
                room: '冷冻机房',
                status: '在用',
          },
            {
                machine_no: '00241',
                machine_name: '压力容器1',
                machine_kind: '压力容器',
                machine_brand: '12-110-15',
                machine_type: '—',
                createTime: '2012-04-01',
                usedTime: '2013-01-01',
                building: '地下一层',
                room: '冷冻机房',
                status: '在用',
          },
            {
                machine_no: '00242',
                machine_name: '压力容器2',
                machine_kind: '压力容器',
                machine_brand: '12-110-10',
                machine_type: '—',
                createTime: '2012-04-01',
                usedTime: '2013-01-01',
                building: '地下一层',
                room: '冷冻机房',
                status: '在用',
          },
            {
                machine_no: '00243',
                machine_name: '压力容器3',
                machine_kind: '压力容器',
                machine_brand: '12-110-8',
                machine_type: '—',
                createTime: '2012-04-01',
                usedTime: '2013-01-01',
                building: '地下一层',
                room: '冷冻机房',
                status: '在用',
          },
            {
                machine_no: '00251',
                machine_name: '冰蓄冷泵1',
                machine_kind: '冰蓄冷泵',
                machine_brand: 'YKGCEVP85C5G-HP',
                machine_type: '—',
                createTime: '2012-04-01',
                usedTime: '2013-01-01',
                building: '地下一层',
                room: '冷冻机房',
                status: '在用',
          },
        ],
        tableData2: [
            {
                machine_no: '00252',
                machine_name: '冰蓄冷泵2',
                machine_kind: '冰蓄冷泵',
                machine_brand: 'YKGCEVP85C5G-HP',
                machine_type: '—',
                createTime: '2012-04-01',
                usedTime: '2013-01-01',
                building: '地下一层',
                room: '冷冻机房',
                status: '在用',
          },
            {
                machine_no: '00253',
                machine_name: '冰蓄冷泵3',
                machine_kind: '冰蓄冷泵',
                machine_brand: 'YKGCEVP85C5G-HP',
                machine_type: '—',
                createTime: '2012-04-01',
                usedTime: '2013-01-01',
                building: '地下一层',
                room: '冷冻机房',
                status: '在用',
          },
            {
                machine_no: '00254',
                machine_name: '冰蓄冷泵4',
                machine_kind: '冰蓄冷泵',
                machine_brand: 'YKGCEVP85C5G-HP',
                machine_type: '—',
                createTime: '2012-04-01',
                usedTime: '2013-01-01',
                building: '地下一层',
                room: '冷冻机房',
                status: '在用',
          },
            {
                machine_no: '00255',
                machine_name: '冰蓄冷泵5',
                machine_kind: '冰蓄冷泵',
                machine_brand: 'YKGCEVP85C5G-HP',
                machine_type: '—',
                createTime: '2012-04-01',
                usedTime: '2013-01-01',
                building: '地下一层',
                room: '冷冻机房',
                status: '在用',
          },
            {
                machine_no: '00256',
                machine_name: '冰蓄冷泵6',
                machine_kind: '冰蓄冷泵',
                machine_brand: 'YKGCEVP85C5G-HP',
                machine_type: '—',
                createTime: '2012-04-01',
                usedTime: '2013-01-01',
                building: '地下一层',
                room: '冷冻机房',
                status: '在用',
          },
            {
                machine_no: '00261',
                machine_name: '板式换热器1',
                machine_kind: '板式换热器',
                machine_brand: 'J107 MGS-10/5',
                machine_type: '—',
                createTime: '2012-04-01',
                usedTime: '2013-01-01',
                building: '地下一层',
                room: '冷冻机房',
                status: '在用',
          },
            {
                machine_no: '00262',
                machine_name: '板式换热器2',
                machine_kind: '板式换热器',
                machine_brand: 'J107 MGS-10/5',
                machine_type: '—',
                createTime: '2012-04-01',
                usedTime: '2013-01-01',
                building: '地下一层',
                room: '冷冻机房',
                status: '在用',
          },
            {
                machine_no: '00263',
                machine_name: '板式换热器3',
                machine_kind: '板式换热器',
                machine_brand: 'J107 MGS-10/5',
                machine_type: '—',
                createTime: '2012-04-01',
                usedTime: '2013-01-01',
                building: '地下一层',
                room: '冷冻机房',
                status: '在用',
          },
            {
                machine_no: '00511',
                machine_name: '热回收式空气处理机组1',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK10-FR4-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'A楼',
                room: '—',
                status: '在用',
          },{
                machine_no: '00512',
                machine_name: '热回收式空气处理机组2',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK10-FR4-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'A楼',
                room: '—',
                status: '在用',
            },
        ],
        tableData3: [
            {
                machine_no: '00513',
                machine_name: '热回收式空气处理机组3',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK10-FR4-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'A楼',
                room: '—',
                status: '在用',
            },
            {
                machine_no: '00514',
                machine_name: '热回收式空气处理机组4',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK10-FR4-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'A楼',
                room: '—',
                status: '在用',
            },
            {
                machine_no: '00515',
                machine_name: '热回收式空气处理机组5',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK10-FR4-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'A楼',
                room: '—',
                status: '在用',
            },
            {
                machine_no: '00516',
                machine_name: '热回收式空气处理机组6',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK10-FR4-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'A楼',
                room: '—',
                status: '在用',
            },
            {
                machine_no: '00517',
                machine_name: '热回收式空气处理机组7',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK10-FR4-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'A楼',
                room: '—',
                status: '在用',
            },
            {
                machine_no: '00518',
                machine_name: '热回收式空气处理机组8',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK10-FR4-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'B楼',
                room: '—',
                status: '在用',
            },
            {
                machine_no: '00519',
                machine_name: '热回收式空气处理机组9',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK10-FR4-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'B楼',
                room: '—',
                status: '在用',
            },
            {
                machine_no: '005110',
                machine_name: '热回收式空气处理机组10',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK10-FR4-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'B楼',
                room: '—',
                status: '在用',
            },
            {
                machine_no: '005111',
                machine_name: '热回收式空气处理机组11',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK10-FR4-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'B楼',
                room: '—',
                status: '在用',
            },{
                machine_no: '005112',
                machine_name: '热回收式空气处理机组12',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK10-FR4-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'B楼',
                room: '—',
                status: '在用',
            },
        ],
        tableData4: [
            {
                machine_no: '005113',
                machine_name: '热回收式空气处理机组13',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK07-FR4-25UY',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'C楼',
                room: '—',
                status: '在用',
            }, {
                machine_no: '005114',
                machine_name: '热回收式空气处理机组14',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK07-FR4-25UY',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'C楼',
                room: '—',
                status: '在用',
          },{
                machine_no: '005115',
                machine_name: '热回收式空气处理机组15',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK07-FR4-25UY',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'C楼',
                room: '—',
                status: '在用',
          }, {
                machine_no: '005116',
                machine_name: '热回收式空气处理机组16',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK07-FR4-25UY',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'C楼',
                room: '—',
                status: '在用',
          },{
                machine_no: '005117',
                machine_name: '热回收式空气处理机组17',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK07-FR4-25UY',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'C楼',
                room: '—',
                status: '在用',
          },{
                machine_no: '005118',
                machine_name: '热回收式空气处理机组18',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK07-FR4-25UY',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'C楼',
                room: '—',
                status: '在用',
          },{
                machine_no: '005119',
                machine_name: '热回收式空气处理机组19',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK07-FR4-25UY',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'C楼',
                room: '—',
                status: '在用',
          },{
                machine_no: '005120',
                machine_name: '热回收式空气处理机组20',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK04-FR4-25UY',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'C楼',
                room: '—',
                status: '在用',
          },{
                machine_no: '005121',
                machine_name: '热回收式空气处理机组21',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK10-FR-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'D楼',
                room: '—',
                status: '在用',
          },{
                machine_no: '005122',
                machine_name: '热回收式空气处理机组22',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK10-FR-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'D楼',
                room: '—',
                status: '在用',
          },
        ],
        tableData5: [
            {
                machine_no: '005123',
                machine_name: '热回收式空气处理机组23',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK28-F4-25UY',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'D楼',
                room: '—',
                status: '在用',
          },
            {
                machine_no: '005124',
                machine_name: '热回收式空气处理机组24',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK28-F4-25UY',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'D楼',
                room: '—',
                status: '在用',
          },
            {
                machine_no: '005125',
                machine_name: '热回收式空气处理机组25',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HZK-35-F4-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'D楼',
                room: '—',
                status: '在用',
          },
            {
                machine_no: '005126',
                machine_name: '热回收式空气处理机组26',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HZK-35-F4-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'D楼',
                room: '—',
                status: '在用',
          },
            {
                machine_no: '005127',
                machine_name: '热回收式空气处理机组27',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HZK-35-F4-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'D楼',
                room: '—',
                status: '在用',
          },
            {
                machine_no: '005128',
                machine_name: '热回收式空气处理机组28',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK10-FR-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'E楼',
                room: '—',
                status: '在用',
          },
            {
                machine_no: '005129',
                machine_name: '热回收式空气处理机组29',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK10-FR-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'E楼',
                room: '—',
                status: '在用',
          },
            {
                machine_no: '005130',
                machine_name: '热回收式空气处理机组30',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK10-FR-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'E楼',
                room: '—',
                status: '在用',
          },
            {
                machine_no: '005131',
                machine_name: '热回收式空气处理机组31',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK10-FR-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'E楼',
                room: '—',
                status: '在用',
          }, {
                machine_no: '005132',
                machine_name: '热回收式空气处理机组32',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK10-FR-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'E楼',
                room: '—',
                status: '在用',
          },
        ],
        tableData6: [
            {
                machine_no: '005133',
                machine_name: '热回收式空气处理机组33',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK10-FR-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'E楼',
                room: '—',
                status: '在用',
          },
            {
                machine_no: '005134',
                machine_name: '热回收式空气处理机组34',
                machine_kind: '热回收式空气处理机组',
                machine_brand: '北京还都人工环境科技有限公司',
                machine_type: 'HJK10-FR-25UZ',
                createTime: '2012-05-01',
                usedTime: '2012-05-01',
                building: 'E楼',
                room: '—',
                status: '在用',
          },
            {
                machine_no: '00521',
                machine_name: '组合式空调机组1',
                machine_kind: '组合式空调机组',
                machine_brand: '弗德里希冷冻设备',
                machine_type: 'FZK-35L',
                createTime: '2013-08-01',
                usedTime: '—',
                building: 'C楼',
                room: '—',
                status: '未用',
          },
            {
                machine_no: '00522',
                machine_name: '组合式空调机组1',
                machine_kind: '组合式空调机组',
                machine_brand: '弗德里希冷冻设备',
                machine_type: 'FZK-35L',
                createTime: '2013-08-01',
                usedTime: '—',
                building: 'C楼',
                room: '—',
                status: '未用',
          },
            {
                machine_no: '00523',
                machine_name: '组合式空调机组1',
                machine_kind: '组合式空调机组',
                machine_brand: '弗德里希冷冻设备',
                machine_type: 'FZK-35L',
                createTime: '2013-08-01',
                usedTime: '—',
                building: 'C楼',
                room: '—',
                status: '未用',
          },
            {
                machine_no: '00524',
                machine_name: '组合式空调机组1',
                machine_kind: '组合式空调机组',
                machine_brand: '弗德里希冷冻设备',
                machine_type: 'FZK-35L',
                createTime: '2013-08-01',
                usedTime: '—',
                building: 'C楼',
                room: '—',
                status: '未用',
          },
        ],
    },
    methods: {
        handleCurrentChange(val) {
            switch (val) {
                case 1:
                    this.tableData = this.tableData1;
                    break;
                case 2:
                    this.tableData = this.tableData2;
                    break;
                case 3:
                    this.tableData = this.tableData3;
                    break;
                case 4:
                    this.tableData = this.tableData4;
                    break;
                case 5:
                    this.tableData = this.tableData5;
                    break;
                case 6:
                    this.tableData = this.tableData6;
                    break;
            }
        },
        /* 获取当前时间然后转换 */
        dateFtt : function (fmt,date) {
            var o = {   
                "M+" : date.getMonth()+1,                 //月份   
                "d+" : date.getDate(),                    //日   
                "h+" : date.getHours(),                   //小时   
                "m+" : date.getMinutes(),                 //分   
                "s+" : date.getSeconds(),                 //秒   
                "q+" : Math.floor((date.getMonth()+3)/3), //季度   
                "S"  : date.getMilliseconds()             //毫秒   
            };   
            if(/(y+)/.test(fmt))   
            fmt=fmt.replace(RegExp.$1, (date.getFullYear()+"").substr(4 - RegExp.$1.length));   
            for(var k in o)   
            if(new RegExp("("+ k +")").test(fmt))   
            fmt = fmt.replace(RegExp.$1, (RegExp.$1.length==1) ? (o[k]) : (("00"+ o[k]).substr((""+ o[k]).length)));   
            return fmt;
        },
        /* 获取Url后的锚点参数 */
        GetUrlPara : function () {
    　　　　var url = document.location.toString();
    　　　　var arrUrl = url.split("#");
    　　　　var para = arrUrl[1];
    　　　　return para;
        },
        //获取URL地址的参数的方法
        getQueryString : function (name,url1){
            var url = url1 || window.location.search.substr(1);
            var reg = new RegExp("(^|&)"+ name +"=([^&]*)(&|$)");
            var r = url.match(reg);
            if(r!=null)return decodeURI(r[2]); return '';
        },
    },
    //做一些初始化，实现函数自执行 
    created : function () {
        setInterval(function(){
            vm.nowTime = vm.dateFtt("yyyy-MM-dd hh:mm:ss",new Date());
        },1000);
    },
    //发起后端请求，拿数据
    mounted : function () {
        this.tableData = this.tableData1;
        document.getElementById("load").style.display = 'none';
    }
    
});
